CONFIG_PATH = '../config.json'

BAD_SEQUENCE_OF_COMMANDS = '503 Bad sequence of commands.'
INVALID_USERNAME_PASSWORD = '403 Invalid username or password.'
USERNAME_OK = '331 User name okey, need password.'
LOGIN_OK = '230 User logged in, proceed.'
NOT_AUTHORIZED = '332 Need account for login.'
MAX_SIZE = 1024
SYNTAX_ERROR = '501 Syntax error in parameters or arguments.'
FILE_EXISTED = '500 File or directory already existed in this path.'
FILE_NOT_EXISTED = '500 File or directory not existed in this path.'
NOT_DIRECTORY = '500 Not a directory.'
UNKNOWN_COMMAND = '500 Unknown command.'
LIST_TRANSFER_DONE = '226 List transfer done.'
CWD_SUCCESS = '250 Successful Change.'